version: "3"

services:
  mysql_master:
    image: mysql:5.7.17
    ports:
        - "3000:3306"
    volumes:
        - "./master/lib/:/var/lib/mysql/"
        - "./master/log/:/var/log/mysql/"
        - "./master/conf.d/:/etc/mysql/conf.d/"
        - "./master/init-db.d:/docker-entrypoint-initdb.d"
    environment:
        - TZ=Asia/Shanghai
        - MYSQL_ROOT_PASSWORD=123456
  mysql_slave:
    image: mysql:5.7.17
    ports:
      - "3001:3306"
    volumes:
      - "./slave/lib/:/var/lib/mysql/"
      - "./slave/log/:/var/log/mysql/"
      - "./slave/conf.d/:/etc/mysql/mysql.conf.d/"
      - "./slave/init-db.d:/docker-entrypoint-initdb.d"
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
    links:
      - mysql_master